name: Docs Deployment

env:
  APP_LOCATION: ''
  OUTPUT_LOCATION: 'packages/website/build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  check_build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build for PR
    env:
      ENABLE_NODE_MONOREPO_BUILD: true
      NODE_VERSION: 22
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@10.9.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build UI
        run: pnpm ui build

      - name: Build Website
        run: pnpm website build

  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          submodules: true

      - name: Deploy
        uses: Azure/static-web-apps-deploy@4d27395796ac319302594769cfe812bd207490b1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          app_location: ${{ env.APP_LOCATION }}
          app_build_command: 'pnpm website build'
          action: 'upload'
          skip_api_build: true
        env:
          CUSTOM_BUILD_COMMAND: corepack enable && corepack prepare pnpm@10.9.0 --activate && pnpm install --frozen-lockfile && pnpm ui build && pnpm website build
          ENABLE_NODE_MONOREPO_BUILD: true
          NODE_VERSION: 22
